name: Build C bindings and core C extension.

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    - name: Install GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build C extension
      run: |
        make CFLAGS="${CFLAGS} -Werror" CXXFLAGS="${CXXFLAGS} -Werror"

    - name: Compile Cython code
      run: |
        cd src/fd_watcher
        python setup.py build_ext --inplace
